import { StyleSheet } from "react-native";
import { getHeight, getWidth } from "../../services/helper";
import { buildVariants, fontFamily } from "../../constants/strings";
import Layout from "../../constants/Layout";
import Env from "../../constants/Env";
import Colors from "../../constants/Colors";

export default styles = StyleSheet.create({
  rowStyle: {
    flexDirection: "row",
  },
  profileView: {
    marginEnd: getWidth(16),
    width: getHeight(72),
    height: getHeight(72),
    borderRadius: getHeight(72) / 2,
    backgroundColor:
      Env.BUILD_VARIANT === buildVariants.COLUMBIA
        ? Colors.primaryColor
        : "#057575",
    alignItems: "center",
    justifyContent: "center",
    //position: "absolute",
    //right: 0,
    // zIndex: 0,
  },
  profileText: {
    color: "#FFFFFF",
    fontFamily: fontFamily.Regular,
    fontSize: getHeight(40),
    fontWeight: "700",
    alignSelf: "center",
    textTransform: "uppercase",
  },
  fieldTitleText: {
    color: "#566267",
    fontWeight: "400",
    fontSize: getHeight(16),
    lineHeight: getHeight(20),
    marginBottom: getHeight(10),
    fontFamily: fontFamily.Regular,
    marginTop: getHeight(16),
  },
  fieldInput: {
    width: Layout.window.width - getWidth(60),
    height: getHeight(40),
    alignItems: "flex-start",
    borderRadius: getHeight(4),
    elevation: 3,
    color: "#1E1F20",
    fontWeight: "400",
    fontSize: getHeight(14),
    fontFamily: fontFamily.Regular,
    shadowColor: "#000000",
    borderColor: "#C5D1D8",
    borderStyle: "solid",
    //shadowOpacity: 0.15,
    borderWidth: 1,
    // shadowOffset: {
    //   height: 4,
    //   width: 0,
    // },
    backgroundColor: "#FFFFFF",
    paddingHorizontal: getWidth(15),
    fontFamily: fontFamily.Regular,
  },
  dropDownView: {
    marginTop: getHeight(10),
    flexDirection: "row",
    width: Layout.window.width - getWidth(60),
    height: getHeight(40),
    alignItems: "flex-start",
    borderRadius: getHeight(4),
    elevation: 3,
    borderColor: "#C5D1D8",
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: getWidth(15),
  },
  dropDownArrow: {
    marginTop: getHeight(18),
    position: "absolute",
    right: getWidth(10),
    width: getHeight(8),
    height: getHeight(5),
  },
  updateProfileButton: {
    height: getHeight(44),
    width: Layout.window.width - getWidth(60),
    borderRadius: getHeight(4),
    backgroundColor: "#E5EDF0",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    marginTop: getHeight(25),
    marginBottom: getHeight(20),
  },
  buttonStyle: {
    height: getHeight(44),
    width: Layout.window.width - getWidth(60),
    borderRadius: getHeight(4),
    borderWidth: getWidth(1),
    borderColor: "#08A88E",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    // padding: 10,
    marginTop: getHeight(20),
    marginBottom: getHeight(20),
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: getHeight(14),
    lineHeight: getHeight(20),
    fontStyle: "normal",
    fontFamily: fontFamily.Regular,
  },
  settingView: {
    paddingHorizontal: getWidth(30),
    marginTop: getHeight(20),
  },
  headingStyle: {
    fontWeight: "600",
    fontSize: getHeight(16),
    lineHeight: getHeight(24),
    fontStyle: "normal",
    color: "#1E1F20",
    fontFamily: fontFamily.Regular,
  },
  textStyle: {
    fontWeight: "400",
    fontSize: getHeight(14),
    lineHeight: getHeight(20),
    fontStyle: "normal",
    color: "#1E1F20",
    marginTop: getHeight(4),
    fontFamily: fontFamily.Regular,
  },
  divider: {
    borderBottomColor: "#E5EDF0",
    borderBottomWidth: 2,
  },
  mainView: {
    flex: 1,
    backgroundColor: "white",
  },
  innerView: {
    paddingHorizontal: getWidth(30),
    paddingTop: getHeight(10),
  },
  profileSettingText: {
    fontFamily: fontFamily.Regular,
    fontSize: getHeight(16),
    marginVertical: getHeight(16),
    fontWeight: "600",
    lineHeight: getHeight(24),
    color: "#1E1F20",
  },
  labelContainer: {
    flexDirection: "row",
  },
  asteriskSymbol: {
    color: "#FF8E3D",
    width: getWidth(40),
    fontWeight: "700",
    height: getHeight(40),
    fontSize: getHeight(30),
    marginTop: -getHeight(10),
    marginStart: getWidth(1),
  },
  loader: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: -getHeight(25),
  },
});
