import { StyleSheet } from "react-native";
import { BALLON_ELEVATION, fontFamily } from "../constants/strings";
import Colors from "../constants/Colors";
import { getHeight, getWidth } from "../services/helper";

const veryLowOpacityInteractiveColor = "#cbfbd7";
const lowOpacityInteractiveColor = "#ccf1dd";
const mediumOpacityInteractiveColor = "#b3e6ca";
const majorInteractionColor = Colors.infoBoxThemeColor;
const majorInteractionColorDarker = "#20B56C";
const newInteractiveColor = Colors.primaryColor;
const newInteractiveColor2 = Colors.borderColor;

export const globalStyles = StyleSheet.create({
  sectionStyle: {
    backgroundColor: "transparent",
    marginLeft: 15,
    paddingLeft: 0,
    paddingRight: 0,
  },

  sectionTitleTextStyle: {
    color: "#000000",
    flex: 1,
    justifyContent: "flex-end",
    marginTop: 5,
    marginLeft: 23,
    marginBottom: 0,
    fontFamily: fontFamily.Regular,
    fontSize: 28,
    fontWeight: "600",
  },
  sectionTitleOutsideCardTextStyle: {
    color: "#000000",
    flex: 1,
    justifyContent: "flex-end",
    marginTop: 0,
    marginLeft: 51,
    marginBottom: 5,
    fontFamily: fontFamily.Regular,
    fontSize: 22,
    fontWeight: "700",
  },
  questionResourceButtonStyleInsideGreenPrevious: {
    margin: 2,
    borderRadius: 8,
    borderColor: "gray",
    borderWidth: 0.3,
    backgroundColor: veryLowOpacityInteractiveColor,
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
    elevation: BALLON_ELEVATION,
    shadowOpacity: 0,
  },
  questionResourceButtonStyleWhite: {
    margin: 2,
    borderRadius: 8,
    borderColor: "gray",
    borderWidth: 0.3,
    paddingVertical: 5,
    backgroundColor: "transparent",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
    elevation: BALLON_ELEVATION,
    shadowOpacity: 0,
  },
  questionResourceButtonStyle: {
    margin: 2,
    borderRadius: 0,
    borderColor: "transparent",
    borderWidth: 0.3,
    backgroundColor: "transparent",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },

  questionResourceButtonTextStyle: {
    margin: 0,
    fontSize: 13,
    color: newInteractiveColor,
    fontWeight: "500",
  },
  questionResourceButtonTextStyleWhite: {
    margin: 0,
    fontSize: 14,
    color: majorInteractionColor,
    fontWeight: "400",
  },
  questionResourceButtonTextStyleCalculator: {
    margin: 0,
    fontSize: 13,
    color: majorInteractionColor,
    fontWeight: "500",
  },
  questionResourceButtonTextStyleCalculatorInsideGreen: {
    margin: 0,
    fontSize: 12,
    color: majorInteractionColor,
    fontWeight: "500",
  },
  multiButtonTextSelected: {
    margin: 0,
    fontSize: 13,
    color: newInteractiveColor2,
    fontWeight: "500",
  },
  multiButtonTextStyle: {
    margin: 0,
    fontSize: 13,
    color: "#989898",
    fontWeight: "500",
  },
  multipleButtonStyleWithInfoSelected: {
    margin: 2.5,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    marginRight: 0,
    borderColor: majorInteractionColor,
    borderRightColor: "darkgray",
    borderWidth: 1.0,
    backgroundColor: "white",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
    elevation: BALLON_ELEVATION,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowRadius: 2,
  },
  multipleButtonStyleWithInfo: {
    margin: 2.5,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    marginRight: 0,
    borderColor: majorInteractionColor,
    borderWidth: 1.0,
    backgroundColor: "white",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
    elevation: BALLON_ELEVATION,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowRadius: 2,
  },
  cardHeaderStyle: {
    margin: 5,
    marginLeft: 4,
    marginEnd: 6,
    marginBottom: 6,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 7,
    paddingBottom: 7,
  },
  multipleButtonInfoStyle: {
    margin: 2.5,
    marginLeft: 0,
    width: 44,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    borderColor: majorInteractionColor,
    borderWidth: 1.0,
    backgroundColor: majorInteractionColor,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    elevation: BALLON_ELEVATION,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowRadius: 2,
  },

  multipleButtonStyle: {
    margin: 2.5,
    borderRadius: 50,
    backgroundColor: "#FFFFFF",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    elevation: BALLON_ELEVATION,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowRadius: 2,
  },
  multipleButtonStyleSelected: {
    margin: 2.5,
    borderRadius: 20,
    backgroundColor: "white",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 0,
    paddingRight: 0,
    elevation: BALLON_ELEVATION,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowRadius: 2,
  },

  questionResourceViewStyle: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "transparent",
  },

  card: {
    minHeight: 100,
    marginLeft: 12,
    marginRight: 12,
    borderRadius: 8,
  },

  cardStyle: {
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 8,
  },

  readableButtonTextStyle: {
    color: majorInteractionColor,
    fontSize: getHeight(16),
    fontFamily: fontFamily.Regular,
    fontWeight: "400",
    lineHeight: getHeight(21.6),
    textDecorationLine: "underline",
  },

  singleCardItem: {
    marginLeft: 15,
    marginRight: 10,
    marginBottom: 10,
    flexDirection: "column",
    alignItems: "flex-start",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },

  firstCardItemStyle: {
    borderTopLeftRadius: getHeight(8),
    borderTopRightRadius: getHeight(8),
    marginTop: getHeight(10),
    marginLeft: getWidth(15),
    marginRight: getWidth(10),
    marginBottom: getHeight(7),
    paddingLeft: 0,
    paddingRight: 0,
  },
  cardItemStyle: {
    marginLeft: 15,
    marginRight: 10,
    marginVertical: 5,
  },
  lastCardItemStyle: {
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    marginLeft: 15,
    marginRight: 10,
    marginBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
  },
  questionTextStyleSub: {
    color: "#7C7C7B",
    fontSize: 13,
    marginBottom: 6,
  },
  questionTextStyleSubBig: {
    color: "#7C7C7B",
    fontSize: 15,
    marginBottom: 6,
  },
  questionTitleTextStyle: {
    color: "black",
    fontWeight: "600",
    fontSize: 15,
  },
});
