import { Platform, StyleSheet } from "react-native";
import { getHeight, getWidth } from "../../services/helper";
import Colors from "../../constants/Colors";
import { fontFamily } from "../../constants/strings";

export default styles = StyleSheet.create({
  cardStyle: {
    marginStart: getWidth(25),
    marginEnd: getWidth(25),
    marginBottom: getWidth(8),
    marginTop: getWidth(8),
    borderRadius: getHeight(20),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: getHeight(5),
    elevation: 8,
    borderColor: "transparent",
    backgroundColor: "white",
  },
  authorText: {
    fontSize: getHeight(13),
    color: "#515151",
    fontFamily: fontFamily.MediumItalic,
    fontWeight: "400",
  },
  descriptionText: {
    fontSize: getHeight(14),
    color: "#515151",
    lineHeight: getHeight(18),
    fontWeight: "400",
    fontFamily: fontFamily.Regular,
  },
  titleText: {
    fontSize: getHeight(18),
    color: "black",
    marginBottom: getHeight(4),
    fontWeight: "600",
    fontFamily: fontFamily.SemiBold,
    flex: 1,
  },
  addButton: {
    borderColor: Colors.button,
    borderRadius: getHeight(50),
    borderWidth: 1,
    alignSelf: "flex-start",
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    backgroundColor: "white",
    shadowRadius: 4,
    padding: getHeight(10),
    paddingHorizontal: getWidth(17),
  },
  buttonText: {
    color: Colors.button,
    fontWeight: "600",
    fontSize: getHeight(16),
    fontFamily: fontFamily.SemiBold,
    lineHeight: getHeight(16),
  },
  addSubsButton: {
    marginTop: getHeight(18),
    marginBottom: getHeight(15),
    marginStart: getWidth(25),
    marginEnd: getWidth(25),
    height: getHeight(53),
    borderColor: Colors.borderColor,
    borderRadius: getHeight(53 / 2),
    borderWidth: 1,
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: {
      height: getHeight(4),
      width: 0,
    },
    backgroundColor: Colors.button,
    shadowRadius: 4,
    justifyContent: "center",
  },
  addSubsButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: getHeight(18),
    fontFamily: fontFamily.SemiBold,
    lineHeight: getHeight(18),
  },
  searchContainer: {
    marginTop: getHeight(18),
    marginStart: getWidth(25),
    marginEnd: getWidth(25),
    borderRadius: getHeight(53 / 2),
    marginBottom: getHeight(15),
    backgroundColor: "white",
    overflow: "hidden",
    position: "relative",
    zIndex: 0,
    paddingBottom: getHeight(9),
  },
  searchInputContainer: {
    alignItems: "center",
    flexDirection: "row",
    height: 53,
    justifyContent: "space-between",
  },
  searchInput: {
    fontSize: getHeight(16),
    fontFamily: fontFamily.Regular,
  },
  sectionTitle: {
    fontSize: getHeight(24),
    fontWeight: "600",
    color: "black",
    fontFamily: fontFamily.SemiBold,
    marginBottom: getHeight(11),
    marginStart: getWidth(33),
  },
  deleteButton: {
    backgroundColor: "#e34b35",
    width: getWidth(90),
    height: null,
    alignItems: "center",
    justifyContent: "center",
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  deleteText: {
    color: "white",
    fontSize: getHeight(19),
    fontFamily: fontFamily.Regular,
  },
  passwordInputContainer: {
    position: "absolute",
    backgroundColor: "#00000040",
    top: 0,
    bottom: 0,
    start: 0,
    end: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  passwordInputInnerContainer: {
    backgroundColor: "#EDEDED",
    borderRadius: getHeight(20),
    alignItems: "center",
    justifyContent: "center",
    width: "78.5%",
    height: "20%",
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowRadius: 4,
  },
  closeButton: {
    position: "absolute",
    end: 0,
    top: 0,
    backgroundColor: "transparent",
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowRadius: 4,
  },
  passwordText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "black",
    marginBottom: 14,
  },
  passwordInput: {
    width: "73.42%",
    textAlign: "center",
    fontSize: 24,
    backgroundColor: "white",
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowRadius: 4,
    borderRadius: 30,
    flex: 0,
    marginBottom: 10,
  },
  emptyStateText: {
    color: "#1E1F20",
    fontWeight: "600",
    fontSize: getHeight(18),
    lineHeight: getHeight(28),
    textAlign: "center",
    width: getWidth(266),
    top: getHeight(24),
  },
  emptyStateSubText: {
    color: "#566267",
    fontWeight: "400",
    fontSize: getHeight(14),
    lineHeight: getHeight(20),
    textAlign: "center",
    top: getHeight(28),
  },
  emptyStateSubView: {
    flexDirection: "row",
    justifyContent: "center",
    alignContent: "center",
  },
  addEmptyStateButton: {
    marginBottom: getHeight(15),
    width: getWidth(132),
    borderColor: Colors.borderColor,
    borderRadius: getHeight(4),
    borderWidth: 1,
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: {
      height: getHeight(4),
      width: 0,
    },
    backgroundColor: "#23C29D",
    shadowRadius: 4,
    justifyContent: "center",
  },
  emptyStateAddSubsButtonText: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: getHeight(16),
    fontFamily: fontFamily.SemiBold,
    lineHeight: getHeight(20),
  },
  searchWrapper: {
    flexDirection: "row",
    alignItems: "center",
  },
});
